server:
  port: 8083
spring:
  application:
    name: order-service  #nacos会把这个当做服务名称
  cloud:
    nacos:
      service-addr: localhost:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public