server:
  port: 8081
spring:
  application:
    name: order-sentinel
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
      #web-context-unify: false 如果使用了链路流控 那么就要配置这个才会生效 因为默认将调用链路收敛了
      datasource:
        flow-rule: #可以自定义
          nacos:
            server-addr: localhost:8848
            username: nacos
            password: nacos
            dataId: order-sentinel-flow-rules
            rule-type: flow

